//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizualAlgoGeom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VizualAlgoGeom.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=149, Height=26}.
        /// </summary>
        internal static System.Drawing.Size _dockingWindowListMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("_dockingWindowListMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=26}.
        /// </summary>
        internal static System.Drawing.Size aboutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("aboutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point BottomToolStripPanel_Location {
            get {
                object obj = ResourceManager.GetObject("BottomToolStripPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=0}.
        /// </summary>
        internal static System.Drawing.Size BottomToolStripPanel_Size {
            get {
                object obj = ResourceManager.GetObject("BottomToolStripPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=199, Height=26}.
        /// </summary>
        internal static System.Drawing.Size closeAlgorithmToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("closeAlgorithmToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool ContentPanel_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("ContentPanel.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=991, Height=728}.
        /// </summary>
        internal static System.Drawing.Size ContentPanel_Size {
            get {
                object obj = ResourceManager.GetObject("ContentPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point control1_Location {
            get {
                object obj = ResourceManager.GetObject("control1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=0}.
        /// </summary>
        internal static System.Drawing.Size control1_Size {
            get {
                object obj = ResourceManager.GetObject("control1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int control1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("control1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size copyToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("copyToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size deleteToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("deleteToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle dockableControl_Dock {
            get {
                object obj = ResourceManager.GetObject("dockableControl.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point dockableControl_Location {
            get {
                object obj = ResourceManager.GetObject("dockableControl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=5,Right=5,Bottom=5}.
        /// </summary>
        internal static System.Windows.Forms.Padding dockableControl_Margin {
            get {
                object obj = ResourceManager.GetObject("dockableControl.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=758, Height=520}.
        /// </summary>
        internal static System.Drawing.Size dockableControl_Size {
            get {
                object obj = ResourceManager.GetObject("dockableControl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int dockableControl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dockableControl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=48, Height=26}.
        /// </summary>
        internal static System.Drawing.Size editToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("editToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=46, Height=26}.
        /// </summary>
        internal static System.Drawing.Size fileToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("fileToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=54, Height=26}.
        /// </summary>
        internal static System.Drawing.Size helpToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("helpToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point LeftToolStripPanel_Location {
            get {
                object obj = ResourceManager.GetObject("LeftToolStripPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=0}.
        /// </summary>
        internal static System.Drawing.Size LeftToolStripPanel_Size {
            get {
                object obj = ResourceManager.GetObject("LeftToolStripPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave failed. Please try to save manually..
        /// </summary>
        internal static string MainForm_AutosaveFailed {
            get {
                return ResourceManager.GetString("MainForm_AutosaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave succeeded..
        /// </summary>
        internal static string MainForm_AutosaveSucceeded {
            get {
                return ResourceManager.GetString("MainForm_AutosaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosaving....
        /// </summary>
        internal static string MainForm_Autosaving {
            get {
                return ResourceManager.GetString("MainForm_Autosaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point menuStrip_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=2,Right=0,Bottom=2}.
        /// </summary>
        internal static System.Windows.Forms.Padding menuStrip_Padding {
            get {
                object obj = ResourceManager.GetObject("menuStrip.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=758, Height=30}.
        /// </summary>
        internal static System.Drawing.Size menuStrip_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int menuStrip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=218, Height=26}.
        /// </summary>
        internal static System.Drawing.Size newquestionToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("newquestionToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=199, Height=26}.
        /// </summary>
        internal static System.Drawing.Size newToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("newToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=199, Height=26}.
        /// </summary>
        internal static System.Drawing.Size openToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("openToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size pasteToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("pasteToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        internal static string Program_FatalError {
            get {
                return ResourceManager.GetString("Program_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report the issue to the developer, and attach the snapshot created in {0}.
        /// </summary>
        internal static string Program_PleaseSendIssueReport {
            get {
                return ResourceManager.GetString("Program_PleaseSendIssueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=54, Height=26}.
        /// </summary>
        internal static System.Drawing.Size quizToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("quizToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size redoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("redoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=218, Height=26}.
        /// </summary>
        internal static System.Drawing.Size removeQuestionToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("removeQuestionToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point RightToolStripPanel_Location {
            get {
                object obj = ResourceManager.GetObject("RightToolStripPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=0}.
        /// </summary>
        internal static System.Drawing.Size RightToolStripPanel_Size {
            get {
                object obj = ResourceManager.GetObject("RightToolStripPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=199, Height=26}.
        /// </summary>
        internal static System.Drawing.Size savaToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("savaToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=199, Height=26}.
        /// </summary>
        internal static System.Drawing.Size saveAsToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("saveAsToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=218, Height=26}.
        /// </summary>
        internal static System.Drawing.Size showToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("showToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=592}.
        /// </summary>
        internal static System.Drawing.Point statusStrip_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=1,Top=0,Right=10,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding statusStrip_Padding {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Padding", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=758, Height=22}.
        /// </summary>
        internal static System.Drawing.Size statusStrip_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int statusStrip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size stLbAction_Size {
            get {
                object obj = ResourceManager.GetObject("stLbAction.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=16}.
        /// </summary>
        internal static System.Drawing.Size stPbAction_Size {
            get {
                object obj = ResourceManager.GetObject("stPbAction.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to None.
        /// </summary>
        internal static System.Windows.Forms.DockStyle toolStrip1_Dock {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=0}.
        /// </summary>
        internal static System.Drawing.Point toolStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=405, Height=42}.
        /// </summary>
        internal static System.Drawing.Size toolStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int toolStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=2,Top=2,Right=2,Bottom=2}.
        /// </summary>
        internal static System.Windows.Forms.Padding toolStripContainer_ContentPanel_Margin {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.ContentPanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=758, Height=520}.
        /// </summary>
        internal static System.Drawing.Size toolStripContainer_ContentPanel_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.ContentPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle toolStripContainer_Dock {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=30}.
        /// </summary>
        internal static System.Drawing.Point toolStripContainer_Location {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=2,Top=2,Right=2,Bottom=2}.
        /// </summary>
        internal static System.Windows.Forms.Padding toolStripContainer_Margin {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=758, Height=562}.
        /// </summary>
        internal static System.Drawing.Size toolStripContainer_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int toolStripContainer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("toolStripContainer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size toolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=42}.
        /// </summary>
        internal static System.Drawing.Size toolStripSeparator1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=6, Height=42}.
        /// </summary>
        internal static System.Drawing.Size toolStripSeparator2_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point TopToolStripPanel_Location {
            get {
                object obj = ResourceManager.GetObject("TopToolStripPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=0}.
        /// </summary>
        internal static System.Drawing.Size TopToolStripPanel_Size {
            get {
                object obj = ResourceManager.GetObject("TopToolStripPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtBegining_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtBegining.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtBegining_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtBegining.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtBegining_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtBegining.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtBegining_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtBegining.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtEnding_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtEnding.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtEnding_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtEnding.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtEnding_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtEnding.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtEnding_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtEnding.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtGoTo_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtGoTo.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtGoTo_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtGoTo.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtGoTo_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtGoTo.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtGoTo_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtGoTo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtNextStep_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtNextStep.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtNextStep_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtNextStep.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtNextStep_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtNextStep.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtNextStep_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtNextStep.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtPause_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtPause.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtPause_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtPause.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtPause_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtPause.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtPause_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtPause.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtPreviousStep_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtPreviousStep.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtPreviousStep_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtPreviousStep.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtPreviousStep_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtPreviousStep.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtPreviousStep_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtPreviousStep.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtSpeedDown_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedDown.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtSpeedDown_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedDown.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtSpeedDown_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedDown.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtSpeedDown_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedDown.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtSpeedUp_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedUp.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtSpeedUp_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedUp.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtSpeedUp_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedUp.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtSpeedUp_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtSpeedUp.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtStart_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtStart.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtStart_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtStart.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtStart_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtStart.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtStart_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtStart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tsBtStop_Image {
            get {
                object obj = ResourceManager.GetObject("tsBtStop.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ToolStripItemImageScaling similar to None.
        /// </summary>
        internal static System.Windows.Forms.ToolStripItemImageScaling tsBtStop_ImageScaling {
            get {
                object obj = ResourceManager.GetObject("tsBtStop.ImageScaling", resourceCulture);
                return ((System.Windows.Forms.ToolStripItemImageScaling)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Magenta].
        /// </summary>
        internal static System.Drawing.Color tsBtStop_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("tsBtStop.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=39}.
        /// </summary>
        internal static System.Drawing.Size tsBtStop_Size {
            get {
                object obj = ResourceManager.GetObject("tsBtStop.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=134, Height=26}.
        /// </summary>
        internal static System.Drawing.Size undoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("undoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=56, Height=26}.
        /// </summary>
        internal static System.Drawing.Size viewToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("viewToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
    }
}
